name: CI/CD Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Docker image with tags
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            malikovdavronbek/soccer-fastapi:latest
            malikovdavronbek/soccer-fastapi:${{ github.sha }}
          load: true

      # 5. Run a container to verify it works (with logs)
      - name: Test Docker container
        run: |
          echo "Starting container for test..."
          docker run --name test-container -d -p 8000:8000 malikovdavronbek/soccer-fastapi:latest
          echo "Sleeping 5 seconds to let container initialize..."
          sleep 5
          echo "Showing container logs:"
          docker logs test-container || true
          echo "Listing all containers:"
          docker ps -a
          echo "Removing test container..."
          docker rm -f test-container
          echo "Container test step completed!"
